### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by nomanaliii** [arackaf/simple-react-bootstrap#2]
When i tried to `import {NavBar} from 'react-simple-bootstrap'` it gives me error 

`Uncaught SyntaxError: Unexpected token import`

After trying everything i found on internet. I finally commented `import {NavBar} from 'react-simple-bootstrap'` this line. And it works.

**Comment by arackaf** [comment]
Are you using webpack?  If not, what are you using to load this utility? 

There's an ES5 dist file in the dist folder called `simple-react-bootstrap-script-tag.js`

The docs https://www.npmjs.com/package/simple-react-bootstrap have a few notes under "Installation" on using that.
